#!/usr/bin/env python3
"""
Training Script for FLUX.1-schnell LoRA using ostris/ai-toolkit

This script handles ONLY training and config generation. Inference has
been split out into flux_infer.py.

Key features:
- Generates a commented flux_training_config.yaml (preserves guidance notes)
- Validates Hugging Face token before training
- Supports a --generate-config-only mode
- Uses config.json for dataset paths and trigger word
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path
from dotenv import load_dotenv  # type: ignore

from config import get_config


def validate_hf_token(token):
    """Return True if token appears valid via Hugging Face whoami."""
    if not token:
        return False
    try:
        from huggingface_hub import whoami
        info = whoami(token=token)
        print(info)
        return True
    except Exception as e:  # noqa: BLE001
        print(f"Warning: token validation error: {e}")
        return False


def create_flux_config(
    dataset_dir,
    yaml_config_path,
    trigger_word=None,
    steps: int = 800,
):
    """Create commented YAML config for training and return path.

    Args:
        dataset_dir: Path to the dataset directory with images
        yaml_config_path: Full path where the YAML config should be saved
        trigger_word: Optional trigger word for the model
        steps: Number of training steps

    Output structure: yaml_config_path.parent/
      - flux_training_config.yaml (saved here)
      - samples/ (generated by ai-toolkit)
      - weights/ (LoRA checkpoints)
    """
    tw = trigger_word or ""

    def _q(v: object) -> str:
        s = str(v)
        if "'" in s:
            s = s.replace("'", "''")
        return f"'{s}'"

    # Organize output under model_name subdirectory
    yaml_config_path = Path(yaml_config_path)
    model_output_dir = yaml_config_path.parent
    model_output_dir.mkdir(parents=True, exist_ok=True)

    out_dir_q = _q(model_output_dir)
    data_dir_q = _q(dataset_dir)
    ptw = f"photo of {tw} " if tw else ""
    model_name = "flux_lora"  # Model name derived from directory structure
    lines = [
        "# FLUX.1-schnell LoRA Training Configuration",
        "# Auto-generated by finetune_flux_train.py",
        "job: extension",
        "config:",
        f"  name: {model_name}",
        "  process:",
        "    - type: sd_trainer",
        f"      training_folder: {out_dir_q}",
        f"      trigger_word: '{tw}'",
        "      network:",
        "        type: lora",
        "        linear: 16",
        "        linear_alpha: 32",
        "      save:",
        "        dtype: float16",
        "        save_every: 250",
        "        max_step_saves_to_keep: 4",
        "      datasets:",
        f"        - folder_path: {data_dir_q}",
        "          caption_ext: txt",
        "          caption_dropout_rate: 0.05",
        "          shuffle_tokens: false",
        "          cache_latents_to_disk: true",
        "          resolution: [512, 768, 1024]",
        "      train:",
        "        skip_first_sample: false",
        "        batch_size: 1",
        f"        steps: {steps}",
        "        gradient_accumulation_steps: 1",
        "        train_unet: true",
        "        train_text_encoder: false",
        "        gradient_checkpointing: true",
        "        noise_scheduler: flowmatch",
        "        optimizer: adamw8bit",
        "        lr: 1e-4",
        "        ema_config:",
        "          use_ema: true",
        "          ema_decay: 0.99",
        "        dtype: bf16",
        "      model:",
        "        name_or_path: black-forest-labs/FLUX.1-schnell",
        "        assistant_lora_path: ostris/FLUX.1-schnell-training-adapter",
        "        is_flux: true",
        "        quantize: true",
        "      sample:",
        "        sampler: flowmatch",
        "        sample_every: 250",
        "        width: 1024",
        "        prompts:",
        (
            f"          - 'photo {ptw} holding a rabbit, soft lighting, "
            "high detail 8k'"
        ),
        (
            f"          - '{ptw} watching a sunset over mountains, "
            "vibrant colors 8k'"
        ),
        (
            "        neg: 'text, words, writing, sentence, multiple letters, "
            "extra symbols, numbers, logos, watermarks, cartoon'"
        ),
        "        seed: 42",
        "        walk_seed: true",
        "        guidance_scale: 1",
        "        sample_steps: 4",
    ]

    # Save YAML config at the specified path
    yaml_config_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✓ Created training config: {yaml_config_path}")
    print(f"✓ Model output directory: {model_output_dir}")
    return yaml_config_path


def check_ai_toolkit():
    toolkit_path = Path("../ai-toolkit")
    if not toolkit_path.exists():
        print("Error: ai-toolkit not found at ../ai-toolkit")
        print(
            "Clone it: "
            "git clone https://github.com/ostris/ai-toolkit.git .."
        )
        return False
    return True


def run_training(config_path):
    toolkit_path = Path("../ai-toolkit")
    run_script = toolkit_path / "run.py"
    if not run_script.exists():
        print(f"Error: {run_script} not found")
        return False
    print("\nStarting training with ai-toolkit...")
    print(f"Config: {config_path}")
    cmd = [sys.executable, str(run_script), str(config_path.absolute())]
    try:
        result = subprocess.run(cmd, cwd=str(toolkit_path))
        return result.returncode == 0
    except KeyboardInterrupt:  # noqa: PIE786
        print("\nTraining interrupted by user")
        return False
    except Exception as e:  # noqa: BLE001
        print(f"Error running training: {e}")
        return False


def main():

    parser = argparse.ArgumentParser(
        description="FLUX.1-schnell LoRA training"
    )
    parser.add_argument(
        "--generate-config-only",
        action="store_true",
        help="Only generate flux_training_config.yaml and exit",
    )
    parser.add_argument(
        "--trigger-word",
        type=str,
        default=None,
        help="Override trigger word for config generation",
    )
    parser.add_argument(
        "--config-path",
        type=str,
        default="flux_training_config.yaml",
        help="Output path for generated config",
    )

    parser.add_argument(
        "--steps",
        type=int,
        default=800,
        help="Number of training steps to include in config (default: 800)",
    )
    args = parser.parse_args()

    load_dotenv("ENV")
    hf_token = os.getenv("HF_TOKEN") or os.getenv("HUGGINGFACE_TOKEN")
    if not hf_token:
        print("\nMissing HF_TOKEN in ENV file. Add: HF_TOKEN=hf_xxx")
        sys.exit(1)

    if not args.generate_config_only and not validate_hf_token(hf_token):
        print("\nInvalid Hugging Face token or insufficient permissions.")
        print("Check https://huggingface.co/settings/tokens")
        sys.exit(1)

    try:
        config = get_config()
    except FileNotFoundError as e:  # noqa: PERF203
        print(f"Error: {e}")
        print("Create config.json first.")
        sys.exit(1)

    dataset_dir = config.photo_images_dir
    output_dir = config.output_dir
    trigger_word = (
        args.trigger_word
        if args.trigger_word is not None
        else config.trigger_word
    )

    if args.generate_config_only:
        create_flux_config(
            dataset_dir,
            config.flux_training_config_path,
            trigger_word,
            args.steps,
        )
        sys.exit(0)

    if not check_ai_toolkit():
        sys.exit(1)

    if not dataset_dir.exists():
        print(f"Dataset directory does not exist: {dataset_dir}")
        sys.exit(1)

    image_files = list(dataset_dir.glob("*.jpg"))
    image_files += list(dataset_dir.glob("*.jpeg"))
    image_files += list(dataset_dir.glob("*.png"))
    if not image_files:
        print(f"No images found in {dataset_dir}")
        sys.exit(1)
    print(f"Found {len(image_files)} images")

    output_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = config.flux_training_config_path
    create_flux_config(
        dataset_dir,
        yaml_path,
        trigger_word,
        args.steps,
    )

    success = run_training(yaml_path)
    if success:
        print("\nTraining completed successfully!")
        model_output = yaml_path.parent
        print(f"Model output directory: {model_output}")
        print(f"  - Config: {yaml_path}")
        print(f"  - Samples: {model_output / 'samples'}")
        print(f"  - Weights: {model_output}")
    else:
        print("\nTraining failed or interrupted")
        sys.exit(1)


if __name__ == "__main__":
    main()
